export const HOME_MENU_ITEM_TITLE = 'Home';
export const HOME = '/';
export const MANAGE_SUB_MENU_TITLE = 'Manage';
export const MANAGE = '/manage';
export const MANAGE_INGREDIENTS_MENU_ITEM_TITLE = 'Ingredients';
export const MANAGE_INGREDIENTS = `${MANAGE}/ingredients`;
export const MANAGE_PRODUCTS_MENU_ITEM_TITLE = 'Products';
export const MANAGE_PRODUCTS = `${MANAGE}/products`;
export const BILLING_SUB_MENU_TITLE = 'Billing';
export const BILLING = '/billing';
export const BILLING_ALL_OPEN_MENU_ITEM_TITLE = 'All open bills';
export const BILLING_ALL_OPEN = `${BILLING}/open`;
export const BILLING_NEW_MENU_ITEM_TITLE = 'New bill';
export const BILLING_SEARCH_MENU_ITEM_TITLE = 'Search bills';
export const BILLING_SEARCH = `${BILLING}/search`;
export const PAGE_URL_TITLE_MAP = {
  [HOME]: HOME_MENU_ITEM_TITLE,
  [MANAGE]: MANAGE_SUB_MENU_TITLE,
  [MANAGE_INGREDIENTS]: MANAGE_INGREDIENTS_MENU_ITEM_TITLE,
  [MANAGE_PRODUCTS]: MANAGE_PRODUCTS_MENU_ITEM_TITLE,
  [BILLING]: BILLING_SUB_MENU_TITLE,
  [BILLING_ALL_OPEN]: BILLING_ALL_OPEN_MENU_ITEM_TITLE,
  [BILLING_SEARCH]: BILLING_SEARCH_MENU_ITEM_TITLE
}
export const BREADCRUMB_MAP = {
  [MANAGE_INGREDIENTS]: [MANAGE_INGREDIENTS],
  [MANAGE_PRODUCTS]: [MANAGE_PRODUCTS],
  [BILLING_ALL_OPEN]: [BILLING_ALL_OPEN],
  [BILLING_SEARCH]: [BILLING_SEARCH]
};